command: predict.py --checkpoint ../checkpoints/finetune_clean/major-capybara-531_exp1_pos_emb/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10_exp1_pos_emb.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 2.2
  log_shift: 9
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 00:13:42
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 09/10/2024 02:16:14
generation_time: 02:02:28
wall_time_utc: 02:02:31
evaluation_0:
    average_num_of_predictions: '9.387266210029457'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '-0.011808384473382226'
        mean_fpsd_score_similsort: '0.1327852752053582'
        rate_of_BART_wins_probsort: '0.44649891755687265'
        rate_of_BART_wins_similsort: '0.669411221918586'
        rate_of_ties_probsort: '0.08684387976008802'
        rate_of_ties_similsort: '0.08684387976008802'
        ties:
            mean_tie_simils_probsort: '0.7346604050557376'
            mean_tie_simils_similsort: '0.8337816055478467'
            num_of_ties_probsort: '2447'
            num_of_ties_simils_equal_to_1_probsort: '1201'
            num_of_ties_simils_equal_to_1_similsort: '1538'
            num_of_ties_similsort: '2447'
            rate_of_ties_simils_equal_to_1_probsort: '0.4908050674295055'
            rate_of_ties_simils_equal_to_1_similsort: '0.6285247241520229'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:17
    formula_stats:
        num_all_correct_formulas: 43703 / 264505
        num_at_least_one_correct_formula: '14800'
        num_correct_formulas_at_best_prob: '8165'
        num_correct_formulas_at_best_simil: '10512'
        rate_of_all_correct_formulas: '0.16522561010188844'
        rate_of_at_least_one_correct_formula: '0.525251091315612'
        rate_of_correct_formulas_at_best_prob: '0.2897753486886468'
        rate_of_correct_formulas_at_best_simil: '0.37307023458849414'
    hit_at_k_prob: '[(1, 0.11917521382688008), (2, 0.16414096603612877), (3, 0.19324271569010185),
        (4, 0.2134719806934734), (5, 0.2288036341697129), (6, 0.24005394470667565),
        (7, 0.24931681868190367), (8, 0.2559179472619512), (9, 0.26049614934166165),
        (10, 0.26283848528942044)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.829230304161818'
        mean_absolute_mw_difference_best_simil: '11.454798988791836'
        mean_relative_mw_difference_best_prob: 4.07%
        mean_relative_mw_difference_best_simil: 4.33%
        rate_of_exact_mw_prob: '0.2852326365475388'
        rate_of_exact_mw_simil: '0.3303048585725947'
        rate_of_exact_nominal_mw_prob: '0.3509600028391951'
        rate_of_exact_nominal_mw_simil: '0.3772225574049757'
        rate_of_mw_difference_less_than_1_best_prob: '0.4006814068211662'
        rate_of_mw_difference_less_than_1_best_simil: '0.4216914504737907'
    num_datapoints_tested: '28177'
    num_empty_preds: '1'
    num_predictions_at_k_counter: '[28177, 28169, 28148, 28097, 27977, 27707, 27200,
        26127, 23923, 18981]'
    precise_preds_stats:
        num_precise_preds_probsort: '2707'
        num_precise_preds_similsort: '7131'
        rate_of_precise_preds_probsort: '0.09607126379671363'
        rate_of_precise_preds_similsort: '0.25307875217375875'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 5214), (7, 40), (2, 954), (3, 675),
            (4, 294), (5, 110), (6, 65), (9, 19), (8, 23), (10, 12)])
        num_1_hits_as_first_probsort: '3358'
        num_1_hits_as_first_similsort: '7406'
        num_fp_simil_fail_prob: '651'
        num_fp_simil_fail_simil: '275'
        rate_of_1_hits_as_first_probsort: '0.11917521382688008'
        rate_of_1_hits_as_first_similsort: '0.26283848528942044'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '3693'
        num_better_than_threshold_similsort: '7701'
        rate_of_better_than_threshold_probsort: '0.13106434325868616'
        rate_of_better_than_threshold_similsort: '0.27330801717713027'
        threshold: '0.85'
    topk_probsort: '[0.3755074088681804, 0.35117161049603296, 0.33374506699142137,
        0.3211242459202143, 0.31220904400909855, 0.3038185967714133, 0.29711779744326255,
        0.29034188588900844, 0.27839243447187173, 0.2690575683456593]'
    topk_similsort: '[0.5201010685469208, 0.41419358037814763, 0.36596675869898637,
        0.33070314471367024, 0.30218315534849055, 0.2777863444487076, 0.254500608510887,
        0.23168220019631372, 0.20738574118698466, 0.18300605666079622]'
