command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_rcx_inhouse_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
  data_split: all
  dataset_name: RCX_NO
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 15:46:44
generation_time: 00:38:17
wall_time_utc: 00:38:21
evaluation_0:
    average_num_of_predictions: '9.576576576576576'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 26 / 1063
        num_at_least_one_correct_formula: '18'
        num_correct_formulas_at_best_prob: '7'
        num_correct_formulas_at_best_simil: '14'
        rate_of_all_correct_formulas: '0.024459078080903106'
        rate_of_at_least_one_correct_formula: '0.16216216216216217'
        rate_of_correct_formulas_at_best_prob: '0.06306306306306306'
        rate_of_correct_formulas_at_best_simil: '0.12612612612612611'
    hit_at_k_prob: '[(1, 0.02702702702702703), (2, 0.06306306306306306), (3, 0.08108108108108109),
        (4, 0.09009009009009009), (7, 0.0990990990990991), (9, 0.10810810810810811)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '53.042207512900895'
        mean_absolute_mw_difference_best_simil: '45.80184191854053'
        mean_relative_mw_difference_best_prob: 15.87%
        mean_relative_mw_difference_best_simil: 14.38%
        rate_of_exact_mw_prob: '0.06306306306306306'
        rate_of_exact_mw_simil: '0.12612612612612611'
        rate_of_exact_nominal_mw_prob: '0.0990990990990991'
        rate_of_exact_nominal_mw_simil: '0.18018018018018017'
        rate_of_mw_difference_less_than_1_best_prob: '0.13513513513513514'
        rate_of_mw_difference_less_than_1_best_simil: '0.21621621621621623'
    num_datapoints_tested: '111'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[111, 111, 111, 111, 111, 111, 110, 106, 101, 80]'
    precise_preds_stats:
        num_precise_preds_probsort: '3'
        num_precise_preds_similsort: '12'
        rate_of_precise_preds_probsort: '0.02702702702702703'
        rate_of_precise_preds_similsort: '0.10810810810810811'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 12)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '12'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.02702702702702703'
        rate_of_1_hits_as_first_similsort: '0.10810810810810811'
    start_time_utc: 14/12/2024 16:58:53
    threshold_stats:
        num_better_than_threshold_probsort: '5'
        num_better_than_threshold_similsort: '12'
        rate_of_better_than_threshold_probsort: '0.04504504504504504'
        rate_of_better_than_threshold_similsort: '0.10810810810810811'
        threshold: '0.85'
    topk_probsort: '[0.349657738592647, 0.30894545190874595, 0.3003954010160264, 0.296354856937721,
        0.28651439481195085, 0.2686783402548389, 0.2675842445438883, 0.2498674746710543,
        0.2685269982961307, 0.24464905498336478]'
    topk_similsort: '[0.4619404991242423, 0.38587300834997196, 0.32865432200460437,
        0.2987255864133909, 0.27643642706862703, 0.25277708779205366, 0.23181132630539078,
        0.21444336141849224, 0.19370012049178284, 0.16626091406597548]'
