command: predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_test_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/test.jsonl
  data_split: test
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 11/12/2024 13:15:30
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 11/12/2024 20:03:42
generation_time: 06:48:04
wall_time_utc: 06:48:11
evaluation_0:
    average_num_of_predictions: '0.9899529486680582'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 19169 / 27983
        num_at_least_one_correct_formula: '19169'
        num_correct_formulas_at_best_prob: '19169'
        num_correct_formulas_at_best_simil: '19169'
        rate_of_all_correct_formulas: '0.6850230497087517'
        rate_of_at_least_one_correct_formula: '0.6781405879647646'
        rate_of_correct_formulas_at_best_prob: '0.6781405879647646'
        rate_of_correct_formulas_at_best_simil: '0.6781405879647646'
    hit_at_k_prob: '[(1, 0.44093819648353205)]'
    labels_path: data/nist/test.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.7557844120491515'
        mean_absolute_mw_difference_best_simil: '5.7557844120491515'
        mean_relative_mw_difference_best_prob: 2.09%
        mean_relative_mw_difference_best_simil: 2.09%
        rate_of_exact_mw_prob: '0.6676336363957972'
        rate_of_exact_mw_simil: '0.6676336363957972'
        rate_of_exact_nominal_mw_prob: '0.7097675734955956'
        rate_of_exact_nominal_mw_simil: '0.7097675734955956'
        rate_of_mw_difference_less_than_1_best_prob: '0.7277744366222096'
        rate_of_mw_difference_less_than_1_best_simil: '0.7277744366222096'
    num_datapoints_tested: '28267'
    num_empty_preds: '284'
    num_predictions_at_k_counter: '[28267]'
    precise_preds_stats:
        num_precise_preds_probsort: '12041'
        num_precise_preds_similsort: '12041'
        rate_of_precise_preds_probsort: '0.42597375030954826'
        rate_of_precise_preds_similsort: '0.42597375030954826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 12464)])
        num_1_hits_as_first_probsort: '12464'
        num_1_hits_as_first_similsort: '12464'
        num_fp_simil_fail_prob: '423'
        num_fp_simil_fail_simil: '423'
        rate_of_1_hits_as_first_probsort: '0.44093819648353205'
        rate_of_1_hits_as_first_similsort: '0.44093819648353205'
    start_time_utc: 12/12/2024 14:44:19
    threshold_stats:
        num_better_than_threshold_probsort: '12717'
        num_better_than_threshold_similsort: '12717'
        rate_of_better_than_threshold_probsort: '0.4498885626348746'
        rate_of_better_than_threshold_similsort: '0.4498885626348746'
        threshold: '0.85'
    topk_probsort: '[0.667034732256262]'
    topk_similsort: '[0.667034732256262]'
