command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_swgdrug_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
  data_split: all
  dataset_name: SWGDRUG
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 18:50:52
generation_time: 03:42:16
wall_time_utc: 03:42:28
evaluation_0:
    average_num_of_predictions: '8.709756097560975'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:06
    formula_stats:
        num_all_correct_formulas: 3626 / 14284
        num_at_least_one_correct_formula: '1338'
        num_correct_formulas_at_best_prob: '945'
        num_correct_formulas_at_best_simil: '1157'
        rate_of_all_correct_formulas: '0.25385046205544665'
        rate_of_at_least_one_correct_formula: '0.8158536585365853'
        rate_of_correct_formulas_at_best_prob: '0.5762195121951219'
        rate_of_correct_formulas_at_best_simil: '0.7054878048780487'
    hit_at_k_prob: '[(1, 0.32439024390243903), (2, 0.43353658536585366), (3, 0.4878048780487805),
        (4, 0.5182926829268293), (5, 0.5420731707317074), (6, 0.5579268292682927),
        (7, 0.5713414634146341), (8, 0.5786585365853658), (9, 0.5823170731707317),
        (10, 0.5853658536585366)]'
    labels_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.4746085860403'
        mean_absolute_mw_difference_best_simil: '8.73868376121358'
        mean_relative_mw_difference_best_prob: 3.22%
        mean_relative_mw_difference_best_simil: 2.77%
        rate_of_exact_mw_prob: '0.5664634146341463'
        rate_of_exact_mw_simil: '0.6945121951219512'
        rate_of_exact_nominal_mw_prob: '0.600609756097561'
        rate_of_exact_nominal_mw_simil: '0.7103658536585366'
        rate_of_mw_difference_less_than_1_best_prob: '0.624390243902439'
        rate_of_mw_difference_less_than_1_best_simil: '0.724390243902439'
    num_datapoints_tested: '1640'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[1640, 1635, 1630, 1610, 1576, 1524, 1442, 1321,
        1124, 782]'
    precise_preds_stats:
        num_precise_preds_probsort: '531'
        num_precise_preds_similsort: '955'
        rate_of_precise_preds_probsort: '0.32378048780487806'
        rate_of_precise_preds_similsort: '0.5823170731707317'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 947), (6, 2), (2, 9), (3, 2)])
        num_1_hits_as_first_probsort: '532'
        num_1_hits_as_first_similsort: '960'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '5'
        rate_of_1_hits_as_first_probsort: '0.32439024390243903'
        rate_of_1_hits_as_first_similsort: '0.5853658536585366'
    start_time_utc: 14/12/2024 16:59:28
    threshold_stats:
        num_better_than_threshold_probsort: '565'
        num_better_than_threshold_similsort: '987'
        rate_of_better_than_threshold_probsort: '0.3445121951219512'
        rate_of_better_than_threshold_similsort: '0.6018292682926829'
        threshold: '0.85'
    topk_probsort: '[0.6757229277720225, 0.5697347889614924, 0.5249572338373875, 0.4994102004106388,
        0.4886008110025939, 0.4691625141599396, 0.45423387217137345, 0.43872388768078635,
        0.42351635114325326, 0.4089498943261612]'
    topk_similsort: '[0.8242086898354017, 0.63656110536506, 0.5605430429585838, 0.5093210847414539,
        0.46871565731749026, 0.4349445853306925, 0.4020209736269838, 0.36942764052689386,
        0.33950300746815987, 0.3041038540213849]'
