command: predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 11/12/2024 13:15:30
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 11/12/2024 19:57:55
generation_time: 06:42:17
wall_time_utc: 06:42:25
evaluation_0:
    average_num_of_predictions: '0.9898853674983142'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 19069 / 27892
        num_at_least_one_correct_formula: '19069'
        num_correct_formulas_at_best_prob: '19069'
        num_correct_formulas_at_best_simil: '19069'
        rate_of_all_correct_formulas: '0.6836727377025671'
        rate_of_at_least_one_correct_formula: '0.6767576392092842'
        rate_of_correct_formulas_at_best_prob: '0.6767576392092842'
        rate_of_correct_formulas_at_best_simil: '0.6767576392092842'
    hit_at_k_prob: '[(1, 0.43751996309046387)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.871359203562635'
        mean_absolute_mw_difference_best_simil: '5.871359203562635'
        mean_relative_mw_difference_best_prob: 2.10%
        mean_relative_mw_difference_best_simil: 2.10%
        rate_of_exact_mw_prob: '0.6677786847428754'
        rate_of_exact_mw_simil: '0.6677786847428754'
        rate_of_exact_nominal_mw_prob: '0.7094793626007027'
        rate_of_exact_nominal_mw_simil: '0.7094793626007027'
        rate_of_mw_difference_less_than_1_best_prob: '0.7288213791390141'
        rate_of_mw_difference_less_than_1_best_simil: '0.7288213791390141'
    num_datapoints_tested: '28177'
    num_empty_preds: '285'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '11944'
        num_precise_preds_similsort: '11944'
        rate_of_precise_preds_probsort: '0.42389182666713987'
        rate_of_precise_preds_similsort: '0.42389182666713987'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 12328)])
        num_1_hits_as_first_probsort: '12328'
        num_1_hits_as_first_similsort: '12328'
        num_fp_simil_fail_prob: '384'
        num_fp_simil_fail_simil: '384'
        rate_of_1_hits_as_first_probsort: '0.43751996309046387'
        rate_of_1_hits_as_first_similsort: '0.43751996309046387'
    start_time_utc: 12/12/2024 14:44:19
    threshold_stats:
        num_better_than_threshold_probsort: '12619'
        num_better_than_threshold_similsort: '12619'
        rate_of_better_than_threshold_probsort: '0.4478475352237641'
        rate_of_better_than_threshold_similsort: '0.4478475352237641'
        threshold: '0.85'
    topk_probsort: '[0.6640502695344906]'
    topk_similsort: '[0.6640502695344906]'
