command: predict.py --checkpoint ../checkpoints/finetune_clean/smooth-totem-563_exp6_72perc_frozen/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 11:40:08
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 09/10/2024 06:23:29
generation_time: '18:43:17'
wall_time_utc: '18:43:21'
evaluation_0:
    average_num_of_predictions: '8.71462540369805'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.1965157463976536'
        mean_fpsd_score_similsort: '0.3573939904916982'
        rate_of_spectus_wins_probsort: '0.6858430634915001'
        rate_of_spectus_wins_similsort: '0.8499485395890265'
        rate_of_ties_probsort: '0.08379174504028108'
        rate_of_ties_similsort: '0.08379174504028108'
        ties:
            mean_tie_simils_probsort: '0.8329994740910919'
            mean_tie_simils_similsort: '0.8834671297970607'
            num_of_ties_probsort: '2361'
            num_of_ties_simils_equal_to_1_probsort: '1587'
            num_of_ties_simils_equal_to_1_similsort: '1766'
            num_of_ties_similsort: '2361'
            rate_of_ties_simils_equal_to_1_probsort: '0.6721728081321474'
            rate_of_ties_simils_equal_to_1_similsort: '0.747988140618382'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:15
    formula_stats:
        num_all_correct_formulas: 80027 / 245552
        num_at_least_one_correct_formula: '22733'
        num_correct_formulas_at_best_prob: '16750'
        num_correct_formulas_at_best_simil: '19484'
        rate_of_all_correct_formulas: '0.3259065289633153'
        rate_of_at_least_one_correct_formula: '0.8067927742485006'
        rate_of_correct_formulas_at_best_prob: '0.5944564715903041'
        rate_of_correct_formulas_at_best_simil: '0.6914859637292827'
    hit_at_k_prob: '[(1, 0.32090002484295704), (2, 0.4133158249636228), (3, 0.46268232955956984),
        (4, 0.4938070057138801), (5, 0.5169109557440466), (6, 0.5321006494658764),
        (7, 0.5436348795116585), (8, 0.5514781559427903), (9, 0.5562338077155127),
        (10, 0.5580437945842354)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.281620955835482'
        mean_absolute_mw_difference_best_simil: '6.936362608186172'
        mean_relative_mw_difference_best_prob: 2.22%
        mean_relative_mw_difference_best_simil: 2.42%
        rate_of_exact_mw_prob: '0.5826028320971005'
        rate_of_exact_mw_simil: '0.6282783830783972'
        rate_of_exact_nominal_mw_prob: '0.6470525605990701'
        rate_of_exact_nominal_mw_simil: '0.6662526173829719'
        rate_of_mw_difference_less_than_1_best_prob: '0.6916989033608972'
        rate_of_mw_difference_less_than_1_best_simil: '0.6977676828619086'
    num_datapoints_tested: '28177'
    num_empty_preds: '5'
    num_predictions_at_k_counter: '[28177, 28133, 28004, 27780, 27340, 26478, 25025,
        22778, 19036, 12804]'
    precise_preds_stats:
        num_precise_preds_probsort: '8431'
        num_precise_preds_similsort: '15596'
        rate_of_precise_preds_probsort: '0.29921567235688684'
        rate_of_precise_preds_similsort: '0.5535010824431273'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 13003), (2, 1166), (7, 54), (3, 815),
            (5, 171), (4, 340), (6, 106), (8, 28), (10, 26), (9, 15)])
        num_1_hits_as_first_probsort: '9042'
        num_1_hits_as_first_similsort: '15724'
        num_fp_simil_fail_prob: '611'
        num_fp_simil_fail_simil: '128'
        rate_of_1_hits_as_first_probsort: '0.32090002484295704'
        rate_of_1_hits_as_first_similsort: '0.5580437945842354'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '9392'
        num_better_than_threshold_similsort: '15944'
        rate_of_better_than_threshold_probsort: '0.3333215033537992'
        rate_of_better_than_threshold_similsort: '0.5658515810767647'
        threshold: '0.85'
    topk_probsort: '[0.5838315397392162, 0.49831004331829765, 0.46072575256621306,
        0.43793793380456203, 0.42498344488042905, 0.41163230859242295, 0.4010468726262239,
        0.3883319777039165, 0.37227810999274535, 0.35383608052030974]'
    topk_similsort: '[0.7447097838332608, 0.5644500734323679, 0.4953885410113864,
        0.44731310493813164, 0.4086012563496265, 0.37476235823717685, 0.34332118022718106,
        0.3128301259700608, 0.28231562140440053, 0.2504388149032886]'
