command: predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_40bin.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.2
  log_shift: 39
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 01/11/2024 13:53:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 01/11/2024 17:15:26
generation_time: 03:21:58
wall_time_utc: 03:22:02
evaluation_0:
    average_num_of_predictions: '0.9879689108137842'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.25879910813574425'
        mean_fpsd_score_similsort: '0.25879910813574425'
        rate_of_BART_wins_probsort: '0.7187067466373284'
        rate_of_BART_wins_similsort: '0.7187067466373284'
        rate_of_ties_probsort: '0.1448699293750222'
        rate_of_ties_similsort: '0.1448699293750222'
        ties:
            mean_tie_simils_probsort: '0.7227432618398062'
            mean_tie_simils_similsort: '0.7227432618398062'
            num_of_ties_probsort: '4082'
            num_of_ties_simils_equal_to_1_probsort: '1715'
            num_of_ties_simils_equal_to_1_similsort: '1715'
            num_of_ties_similsort: '4082'
            rate_of_ties_simils_equal_to_1_probsort: '0.4201371876531112'
            rate_of_ties_simils_equal_to_1_similsort: '0.4201371876531112'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 18364 / 27838
        num_at_least_one_correct_formula: '18364'
        num_correct_formulas_at_best_prob: '18364'
        num_correct_formulas_at_best_simil: '18364'
        rate_of_all_correct_formulas: '0.6596738271427545'
        rate_of_at_least_one_correct_formula: '0.6517372324945878'
        rate_of_correct_formulas_at_best_prob: '0.6517372324945878'
        rate_of_correct_formulas_at_best_simil: '0.6517372324945878'
    hit_at_k_prob: '[(1, 0.414557972814707)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.039585102740354'
        mean_absolute_mw_difference_best_simil: '6.039585102740354'
        mean_relative_mw_difference_best_prob: 2.18%
        mean_relative_mw_difference_best_simil: 2.18%
        rate_of_exact_mw_prob: '0.6425453383965646'
        rate_of_exact_mw_simil: '0.6425453383965646'
        rate_of_exact_nominal_mw_prob: '0.6835362174823437'
        rate_of_exact_nominal_mw_simil: '0.6835362174823437'
        rate_of_mw_difference_less_than_1_best_prob: '0.7100117116797388'
        rate_of_mw_difference_less_than_1_best_simil: '0.7100117116797388'
    num_datapoints_tested: '28177'
    num_empty_preds: '339'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '11310'
        num_precise_preds_similsort: '11310'
        rate_of_precise_preds_probsort: '0.40139120559321434'
        rate_of_precise_preds_similsort: '0.40139120559321434'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11681)])
        num_1_hits_as_first_probsort: '11681'
        num_1_hits_as_first_similsort: '11681'
        num_fp_simil_fail_prob: '371'
        num_fp_simil_fail_simil: '371'
        rate_of_1_hits_as_first_probsort: '0.414557972814707'
        rate_of_1_hits_as_first_similsort: '0.414557972814707'
    start_time_utc: 04/11/2024 14:14:45
    threshold_stats:
        num_better_than_threshold_probsort: '11959'
        num_better_than_threshold_similsort: '11959'
        rate_of_better_than_threshold_probsort: '0.42442417574617597'
        rate_of_better_than_threshold_similsort: '0.42442417574617597'
        threshold: '0.85'
    topk_probsort: '[0.6461149014773069]'
    topk_similsort: '[0.6461149014773069]'
evaluation_1:
    average_num_of_predictions: '0.9879689108137842'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.25879910813574425'
        mean_fpsd_score_similsort: '0.25879910813574425'
        rate_of_BART_wins_probsort: '0.7187067466373284'
        rate_of_BART_wins_similsort: '0.7187067466373284'
        rate_of_ties_probsort: '0.1448699293750222'
        rate_of_ties_similsort: '0.1448699293750222'
        ties:
            mean_tie_simils_probsort: '0.7227432618398062'
            mean_tie_simils_similsort: '0.7227432618398062'
            num_of_ties_probsort: '4082'
            num_of_ties_simils_equal_to_1_probsort: '1715'
            num_of_ties_simils_equal_to_1_similsort: '1715'
            num_of_ties_similsort: '4082'
            rate_of_ties_simils_equal_to_1_probsort: '0.4201371876531112'
            rate_of_ties_simils_equal_to_1_similsort: '0.4201371876531112'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:33
    formula_stats:
        num_all_correct_formulas: 18364 / 27838
        num_at_least_one_correct_formula: '18364'
        num_correct_formulas_at_best_prob: '18364'
        num_correct_formulas_at_best_simil: '18364'
        rate_of_all_correct_formulas: '0.6596738271427545'
        rate_of_at_least_one_correct_formula: '0.6517372324945878'
        rate_of_correct_formulas_at_best_prob: '0.6517372324945878'
        rate_of_correct_formulas_at_best_simil: '0.6517372324945878'
    hit_at_k_prob: '[(1, 0.414557972814707)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.039585102740354'
        mean_absolute_mw_difference_best_simil: '6.039585102740354'
        mean_relative_mw_difference_best_prob: 2.18%
        mean_relative_mw_difference_best_simil: 2.18%
        rate_of_exact_mw_prob: '0.6425453383965646'
        rate_of_exact_mw_simil: '0.6425453383965646'
        rate_of_exact_nominal_mw_prob: '0.6835362174823437'
        rate_of_exact_nominal_mw_simil: '0.6835362174823437'
        rate_of_mw_difference_less_than_1_best_prob: '0.7100117116797388'
        rate_of_mw_difference_less_than_1_best_simil: '0.7100117116797388'
    num_datapoints_tested: '28177'
    num_empty_preds: '339'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '11310'
        num_precise_preds_similsort: '11310'
        rate_of_precise_preds_probsort: '0.40139120559321434'
        rate_of_precise_preds_similsort: '0.40139120559321434'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11681)])
        num_1_hits_as_first_probsort: '11681'
        num_1_hits_as_first_similsort: '11681'
        num_fp_simil_fail_prob: '371'
        num_fp_simil_fail_simil: '371'
        rate_of_1_hits_as_first_probsort: '0.414557972814707'
        rate_of_1_hits_as_first_similsort: '0.414557972814707'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '11959'
        num_better_than_threshold_similsort: '11959'
        rate_of_better_than_threshold_probsort: '0.42442417574617597'
        rate_of_better_than_threshold_similsort: '0.42442417574617597'
        threshold: '0.85'
    topk_probsort: '[0.6461149014773069]'
    topk_similsort: '[0.6461149014773069]'
