command: predict.py --checkpoint ../checkpoints/finetune_clean/effortless-river-558_exp4_rassp_neims/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 00:21:08
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 08/10/2024 19:00:38
generation_time: '18:39:26'
wall_time_utc: '18:39:29'
evaluation_0:
    average_num_of_predictions: '8.520317989849877'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23299127452922297'
        mean_fpsd_score_similsort: '0.3888562100713938'
        rate_of_BART_wins_probsort: '0.7083436845654257'
        rate_of_BART_wins_similsort: '0.8671966497497959'
        rate_of_ties_probsort: '0.08428860418071477'
        rate_of_ties_similsort: '0.08428860418071477'
        ties:
            mean_tie_simils_probsort: '0.8563116113216802'
            mean_tie_simils_similsort: '0.8918014921707919'
            num_of_ties_probsort: '2375'
            num_of_ties_simils_equal_to_1_probsort: '1668'
            num_of_ties_simils_equal_to_1_similsort: '1790'
            num_of_ties_similsort: '2375'
            rate_of_ties_simils_equal_to_1_probsort: '0.7023157894736842'
            rate_of_ties_simils_equal_to_1_similsort: '0.7536842105263157'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:14
    formula_stats:
        num_all_correct_formulas: 72762 / 240077
        num_at_least_one_correct_formula: '23136'
        num_correct_formulas_at_best_prob: '17438'
        num_correct_formulas_at_best_simil: '20214'
        rate_of_all_correct_formulas: '0.3030777625511815'
        rate_of_at_least_one_correct_formula: '0.8210952195052702'
        rate_of_correct_formulas_at_best_prob: '0.6188735493487596'
        rate_of_correct_formulas_at_best_simil: '0.7173936189090393'
    hit_at_k_prob: '[(1, 0.3664336160698442), (2, 0.46470525605990703), (3, 0.5150654789367214),
        (4, 0.5451964368101643), (5, 0.5664549100330056), (6, 0.5806863754125705),
        (7, 0.5911913972388828), (8, 0.5981829151435568), (9, 0.601518969372183),
        (10, 0.6030805266706889)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.491834070314148'
        mean_absolute_mw_difference_best_simil: '6.9884894149280905'
        mean_relative_mw_difference_best_prob: 2.30%
        mean_relative_mw_difference_best_simil: 2.44%
        rate_of_exact_mw_prob: '0.6093977357419171'
        rate_of_exact_mw_simil: '0.6452070837917451'
        rate_of_exact_nominal_mw_prob: '0.6569897434077439'
        rate_of_exact_nominal_mw_simil: '0.6720019874365617'
        rate_of_mw_difference_less_than_1_best_prob: '0.6926216417645598'
        rate_of_mw_difference_less_than_1_best_simil: '0.6953188770983426'
    num_datapoints_tested: '28177'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[28177, 28096, 27874, 27464, 26786, 25706, 24082,
        21738, 18094, 12062]'
    precise_preds_stats:
        num_precise_preds_probsort: '9803'
        num_precise_preds_similsort: '16877'
        rate_of_precise_preds_probsort: '0.3479078681193882'
        rate_of_precise_preds_similsort: '0.5989636937928098'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 14156), (8, 18), (2, 1312), (4, 326),
            (3, 909), (5, 135), (6, 75), (7, 44), (10, 5), (9, 13)])
        num_1_hits_as_first_probsort: '10325'
        num_1_hits_as_first_similsort: '16993'
        num_fp_simil_fail_prob: '522'
        num_fp_simil_fail_simil: '116'
        rate_of_1_hits_as_first_probsort: '0.3664336160698442'
        rate_of_1_hits_as_first_similsort: '0.6030805266706889'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '10636'
        num_better_than_threshold_similsort: '17196'
        rate_of_better_than_threshold_probsort: '0.37747098697519255'
        rate_of_better_than_threshold_similsort: '0.6102849842069773'
        threshold: '0.85'
    topk_probsort: '[0.6203070678707856, 0.5193264098911697, 0.4767841704795092, 0.4507375008324008,
        0.4297112496662881, 0.4143862145283611, 0.3970177634300669, 0.3797737508034111,
        0.3583013445271639, 0.3363288585422788]'
    topk_similsort: '[0.7761720034129564, 0.5828032311560951, 0.5088043725361762,
        0.4550883448215791, 0.4119743958946606, 0.3750764848303209, 0.3400852500468524,
        0.30571558332949034, 0.27208697368552714, 0.240093539699504]'
