command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp8_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_test_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/test.jsonl
  data_split: test
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/01/2025 10:52:35
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 07/01/2025 00:57:03
generation_time: '14:03:54'
wall_time_utc: '14:04:27'
