command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_mona_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
  data_split: all
  dataset_name: MONA_GCMS
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 22:21:51
generation_time: 07:13:15
wall_time_utc: 07:13:27
evaluation_0:
    average_num_of_predictions: '8.918245264207378'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:11
    formula_stats:
        num_all_correct_formulas: 7188 / 44725
        num_at_least_one_correct_formula: '2622'
        num_correct_formulas_at_best_prob: '1893'
        num_correct_formulas_at_best_simil: '2187'
        rate_of_all_correct_formulas: '0.16071548351034098'
        rate_of_at_least_one_correct_formula: '0.5228315054835494'
        rate_of_correct_formulas_at_best_prob: '0.37746759720837486'
        rate_of_correct_formulas_at_best_simil: '0.43609172482552344'
    hit_at_k_prob: '[(1, 0.20797607178464605), (2, 0.26739780658025925), (3, 0.294715852442672),
        (4, 0.3160518444666002), (5, 0.33020937188434696), (6, 0.3383848454636092),
        (7, 0.3427716849451645), (8, 0.3459621136590229), (9, 0.34795613160518446),
        (10, 0.34875373878364907)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '58.77634136979266'
        mean_absolute_mw_difference_best_simil: '61.306971317775705'
        mean_relative_mw_difference_best_prob: 34.81%
        mean_relative_mw_difference_best_simil: 35.82%
        rate_of_exact_mw_prob: '0.3732801595214357'
        rate_of_exact_mw_simil: '0.4137587238285145'
        rate_of_exact_nominal_mw_prob: '0.4195413758723828'
        rate_of_exact_nominal_mw_simil: '0.4412761714855434'
        rate_of_mw_difference_less_than_1_best_prob: '0.4412761714855434'
        rate_of_mw_difference_less_than_1_best_simil: '0.45663010967098705'
    num_datapoints_tested: '5015'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[5015, 4986, 4935, 4866, 4796, 4689, 4514, 4254,
        3787, 2883]'
    precise_preds_stats:
        num_precise_preds_probsort: '1001'
        num_precise_preds_similsort: '1711'
        rate_of_precise_preds_probsort: '0.1996011964107677'
        rate_of_precise_preds_similsort: '0.3411764705882353'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1611), (2, 93), (3, 32), (4, 6), (5,
            4), (6, 1), (7, 1), (9, 1)])
        num_1_hits_as_first_probsort: '1043'
        num_1_hits_as_first_similsort: '1749'
        num_fp_simil_fail_prob: '42'
        num_fp_simil_fail_simil: '38'
        rate_of_1_hits_as_first_probsort: '0.20797607178464605'
        rate_of_1_hits_as_first_similsort: '0.34875373878364907'
    start_time_utc: 14/12/2024 16:57:49
    threshold_stats:
        num_better_than_threshold_probsort: '1070'
        num_better_than_threshold_similsort: '1768'
        rate_of_better_than_threshold_probsort: '0.21335992023928216'
        rate_of_better_than_threshold_similsort: '0.3525423728813559'
        threshold: '0.85'
    topk_probsort: '[0.41229481626977116, 0.32603652232456515, 0.2943237988778277,
        0.2789876409727479, 0.26672476502558434, 0.255208880981459, 0.24051008775535515,
        0.22885312212198136, 0.22130182708577112, 0.20809481990239873]'
    topk_similsort: '[0.540775072459505, 0.37257463269598173, 0.31624623331880364,
        0.2794713860176426, 0.252113663657167, 0.22731368686917014, 0.20489891399305518,
        0.1821763530532273, 0.1616512155382562, 0.13843663981544815]'
