command: predict.py --checkpoint ../checkpoints/finetune_clean/avid-rain-560_exp4_rassp/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 00:21:04
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 08/10/2024 19:03:34
generation_time: '18:42:25'
wall_time_utc: '18:42:29'
evaluation_0:
    average_num_of_predictions: '8.519821130709444'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.21425322705045674'
        mean_fpsd_score_similsort: '0.36517860259919177'
        rate_of_spectus_wins_probsort: '0.6922312524399333'
        rate_of_spectus_wins_similsort: '0.8540653724669056'
        rate_of_ties_probsort: '0.09000248429570216'
        rate_of_ties_similsort: '0.09000248429570216'
        ties:
            mean_tie_simils_probsort: '0.8313163025767746'
            mean_tie_simils_similsort: '0.867803210591032'
            num_of_ties_probsort: '2536'
            num_of_ties_simils_equal_to_1_probsort: '1667'
            num_of_ties_simils_equal_to_1_similsort: '1781'
            num_of_ties_similsort: '2536'
            rate_of_ties_simils_equal_to_1_probsort: '0.6573343848580442'
            rate_of_ties_simils_equal_to_1_similsort: '0.7022870662460567'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:15
    formula_stats:
        num_all_correct_formulas: 66612 / 240063
        num_at_least_one_correct_formula: '22418'
        num_correct_formulas_at_best_prob: '16523'
        num_correct_formulas_at_best_simil: '19233'
        rate_of_all_correct_formulas: '0.2774771622449107'
        rate_of_at_least_one_correct_formula: '0.7956134435887426'
        rate_of_correct_formulas_at_best_prob: '0.5864002555275579'
        rate_of_correct_formulas_at_best_simil: '0.6825779891400788'
    hit_at_k_prob: '[(1, 0.33995812187244917), (2, 0.43166412322106684), (3, 0.47854633211484543),
        (4, 0.5068673031195656), (5, 0.5273095077545515), (6, 0.541328033502502),
        (7, 0.5509812968023565), (8, 0.5582212442772474), (9, 0.5618767079532953),
        (10, 0.5632963054973915)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.936996539710899'
        mean_absolute_mw_difference_best_simil: '7.742563565183093'
        mean_relative_mw_difference_best_prob: 2.54%
        mean_relative_mw_difference_best_simil: 2.79%
        rate_of_exact_mw_prob: '0.5766760123504986'
        rate_of_exact_mw_simil: '0.6080491180750257'
        rate_of_exact_nominal_mw_prob: '0.6212158852965184'
        rate_of_exact_nominal_mw_simil: '0.6363700890797459'
        rate_of_mw_difference_less_than_1_best_prob: '0.655428186109238'
        rate_of_mw_difference_less_than_1_best_simil: '0.6606097171451893'
    num_datapoints_tested: '28177'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[28177, 28051, 27816, 27422, 26749, 25675, 24034,
        21715, 18101, 12325]'
    precise_preds_stats:
        num_precise_preds_probsort: '9083'
        num_precise_preds_similsort: '15744'
        rate_of_precise_preds_probsort: '0.32235511232565567'
        rate_of_precise_preds_similsort: '0.5587535933562835'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 13024), (2, 1304), (9, 12), (4, 312),
            (3, 961), (5, 132), (6, 76), (7, 30), (10, 7), (8, 14)])
        num_1_hits_as_first_probsort: '9579'
        num_1_hits_as_first_similsort: '15872'
        num_fp_simil_fail_prob: '496'
        num_fp_simil_fail_simil: '128'
        rate_of_1_hits_as_first_probsort: '0.33995812187244917'
        rate_of_1_hits_as_first_similsort: '0.5632963054973915'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '9924'
        num_better_than_threshold_similsort: '16088'
        rate_of_better_than_threshold_probsort: '0.3522021506902793'
        rate_of_better_than_threshold_similsort: '0.5709621322355112'
        threshold: '0.85'
    topk_probsort: '[0.6015690203920193, 0.5085980510233635, 0.4671327369498187, 0.4428538183668607,
        0.4237929012998202, 0.406897021521644, 0.3901248254991619, 0.37045260950663983,
        0.3498947274133244, 0.32681095410945854]'
    topk_similsort: '[0.7524943959407544, 0.5706176903843408, 0.499238090388192, 0.44763489810803936,
        0.4059528504721775, 0.3690239754925831, 0.3337517033260062, 0.2995944647465822,
        0.2659337517432779, 0.23321593084833614]'
