command: predict.py --checkpoint ../checkpoints/finetune_clean/royal-violet-583_exp2_lin_10000/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10_exp2_lin_10000.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  do_log_binning: false
  inference_mode: true
  linear_bin_decimals: 4
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 14/12/2024 13:26:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 14/12/2024 22:51:38
generation_time: 09:24:50
wall_time_utc: 09:24:54
