command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp8_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_mona_oo_beam10.yaml
cuda_visible_devices: GPU-83f9775f-f502-4683-141b-c510e5f0c080
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_only.jsonl
  data_split: all
  dataset_name: MONA_GCMS_overlaps_only
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/01/2025 02:09:56
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 07/01/2025 06:06:47
generation_time: 03:56:47
wall_time_utc: 03:56:50
