command: ../predict.py --checkpoint ../checkpoints/finetune_clean/hopeful-rain-557_exp4_rassp_neims_nist/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 31/10/2024 11:52:50
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 01/11/2024 19:33:07
generation_time: 07:40:14
wall_time_utc: 07:40:17
evaluation_0:
    average_num_of_predictions: '8.567803527699898'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.2368404984013023'
        mean_fpsd_score_similsort: '0.38789486949632096'
        rate_of_spectus_wins_probsort: '0.7123540476274977'
        rate_of_spectus_wins_similsort: '0.865280193065266'
        rate_of_ties_probsort: '0.08691485963729283'
        rate_of_ties_similsort: '0.08691485963729283'
        ties:
            mean_tie_simils_probsort: '0.8457270822562912'
            mean_tie_simils_similsort: '0.8799536872396336'
            num_of_ties_probsort: '2449'
            num_of_ties_simils_equal_to_1_probsort: '1684'
            num_of_ties_simils_equal_to_1_similsort: '1795'
            num_of_ties_similsort: '2449'
            rate_of_ties_simils_equal_to_1_probsort: '0.6876276031033075'
            rate_of_ties_simils_equal_to_1_similsort: '0.7329522253981217'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:14
    formula_stats:
        num_all_correct_formulas: 72758 / 241415
        num_at_least_one_correct_formula: '23169'
        num_correct_formulas_at_best_prob: '17659'
        num_correct_formulas_at_best_simil: '20282'
        rate_of_all_correct_formulas: '0.3013814386015782'
        rate_of_at_least_one_correct_formula: '0.8222663874791497'
        rate_of_correct_formulas_at_best_prob: '0.6267168257798914'
        rate_of_correct_formulas_at_best_simil: '0.7198069347340029'
    hit_at_k_prob: '[(1, 0.372360435816446), (2, 0.4667636724988466), (3, 0.5148880292437094),
        (4, 0.5443446782837066), (5, 0.5641125740852468), (6, 0.5787344287894381),
        (7, 0.5897363097561841), (8, 0.5963374383362317), (9, 0.5997089825034603),
        (10, 0.6015899492493878)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.335107065868846'
        mean_absolute_mw_difference_best_simil: '6.984415833781934'
        mean_relative_mw_difference_best_prob: 2.27%
        mean_relative_mw_difference_best_simil: 2.44%
        rate_of_exact_mw_prob: '0.6166021932782056'
        rate_of_exact_mw_simil: '0.6463782517656245'
        rate_of_exact_nominal_mw_prob: '0.6646555701458636'
        rate_of_exact_nominal_mw_simil: '0.6749476523405614'
        rate_of_mw_difference_less_than_1_best_prob: '0.699897079178053'
        rate_of_mw_difference_less_than_1_best_simil: '0.6993292401604145'
    num_datapoints_tested: '28177'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[28177, 28112, 27947, 27613, 27012, 25946, 24338,
        21940, 18180, 12152]'
    precise_preds_stats:
        num_precise_preds_probsort: '10029'
        num_precise_preds_similsort: '16842'
        rate_of_precise_preds_probsort: '0.35592859424353196'
        rate_of_precise_preds_similsort: '0.5977215459417256'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 14054), (2, 1303), (9, 7), (3, 966),
            (4, 338), (5, 143), (6, 76), (8, 19), (7, 39), (10, 6)])
        num_1_hits_as_first_probsort: '10492'
        num_1_hits_as_first_similsort: '16951'
        num_fp_simil_fail_prob: '463'
        num_fp_simil_fail_simil: '109'
        rate_of_1_hits_as_first_probsort: '0.372360435816446'
        rate_of_1_hits_as_first_similsort: '0.6015899492493878'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '10810'
        num_better_than_threshold_similsort: '17155'
        rate_of_better_than_threshold_probsort: '0.3836462362920112'
        rate_of_better_than_threshold_similsort: '0.6088298967242787'
        threshold: '0.85'
    topk_probsort: '[0.6241562917428649, 0.5205182943531173, 0.4796262688461089, 0.45534144204301685,
        0.43931376074602485, 0.42300226967453325, 0.40682296277935664, 0.3861984479183396,
        0.36301657639043167, 0.3378092531874927]'
    topk_similsort: '[0.7752106628378836, 0.5901058207907819, 0.5160860453148304,
        0.4640993717101926, 0.42137291618240336, 0.38232723074110997, 0.346063828200274,
        0.3107983756122462, 0.2749080659338169, 0.23918689760575734]'
