command: predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 09/10/2024 13:43:53
tokenizer_path: tokenizer/tokenizer_mf10M.model
evaluation_0:
    average_num_of_predictions: '0.9850099791923224'
    db_search:
        mean_db_score: '0.3869110860104594'
        mean_fpsd_score_probsort: '0.21368125980119532'
        mean_fpsd_score_similsort: '0.21368125980119532'
        rate_of_BART_wins_probsort: '0.6823219669625037'
        rate_of_BART_wins_similsort: '0.6823219669625037'
        rate_of_ties_probsort: '0.12756380313389104'
        rate_of_ties_similsort: '0.12756380313389104'
        ties:
            mean_tie_simils_probsort: '0.7316134013714086'
            mean_tie_simils_similsort: '0.7316134013714086'
            num_of_ties_probsort: '3004'
            num_of_ties_simils_equal_to_1_probsort: '1304'
            num_of_ties_simils_equal_to_1_similsort: '1304'
            num_of_ties_similsort: '3004'
            rate_of_ties_simils_equal_to_1_probsort: '0.4340878828229028'
            rate_of_ties_simils_equal_to_1_similsort: '0.4340878828229028'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:20
    formula_stats:
        num_all_correct_formulas: 14123 / 23196
        num_at_least_one_correct_formula: '14123'
        num_correct_formulas_at_best_prob: '14123'
        num_correct_formulas_at_best_simil: '14123'
        rate_of_all_correct_formulas: '0.6088549749956889'
        rate_of_at_least_one_correct_formula: '0.5997282262516455'
        rate_of_correct_formulas_at_best_prob: '0.5997282262516455'
        rate_of_correct_formulas_at_best_simil: '0.5997282262516455'
    hit_at_k_prob: '[(1, 0.3565756507707334)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_mw_difference_best_prob: '6.8363120461613835'
        mean_mw_difference_best_simil: '6.8363120461613835'
        rate_of_exact_mw_prob: '0.5899613571701559'
        rate_of_exact_mw_simil: '0.5899613571701559'
        rate_of_exact_nominal_mw_prob: '0.6371820459467493'
        rate_of_exact_nominal_mw_simil: '0.6371820459467493'
        rate_of_mw_difference_less_than_1_best_prob: '0.6688182088411397'
        rate_of_mw_difference_less_than_1_best_simil: '0.6688182088411397'
    num_datapoints_tested: '23549'
    num_empty_preds: '353'
    num_predictions_at_k_counter: '[23549]'
    precise_preds_stats:
        num_precise_preds_probsort: '8077'
        num_precise_preds_similsort: '8077'
        rate_of_precise_preds_probsort: '0.3429869633530086'
        rate_of_precise_preds_similsort: '0.3429869633530086'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8397)])
        num_1_hits_as_first_probsort: '8397'
        num_1_hits_as_first_similsort: '8397'
        num_fp_simil_fail_prob: '320'
        num_fp_simil_fail_simil: '320'
        rate_of_1_hits_as_first_probsort: '0.3565756507707334'
        rate_of_1_hits_as_first_similsort: '0.3565756507707334'
    start_time_utc: 24/10/2024 20:45:40
    threshold_stats:
        num_better_than_threshold_probsort: '8625'
        num_better_than_threshold_similsort: '8625'
        rate_of_better_than_threshold_probsort: '0.36625759055586227'
        rate_of_better_than_threshold_similsort: '0.36625759055586227'
        threshold: '0.85'
    topk_probsort: '[0.6005923458116548]'
    topk_similsort: '[0.6005923458116548]'
