command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_swgdrug_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
  data_split: all
  dataset_name: SWGDRUG
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:22
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 15:50:16
generation_time: 00:41:51
wall_time_utc: 00:41:54
evaluation_0:
    average_num_of_predictions: '0.9926829268292683'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:04
    formula_stats:
        num_all_correct_formulas: 971 / 1628
        num_at_least_one_correct_formula: '971'
        num_correct_formulas_at_best_prob: '971'
        num_correct_formulas_at_best_simil: '971'
        rate_of_all_correct_formulas: '0.5964373464373465'
        rate_of_at_least_one_correct_formula: '0.5920731707317073'
        rate_of_correct_formulas_at_best_prob: '0.5920731707317073'
        rate_of_correct_formulas_at_best_simil: '0.5920731707317073'
    hit_at_k_prob: '[(1, 0.34146341463414637)]'
    labels_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.469426925912888'
        mean_absolute_mw_difference_best_simil: '10.469426925912888'
        mean_relative_mw_difference_best_prob: 3.27%
        mean_relative_mw_difference_best_simil: 3.27%
        rate_of_exact_mw_prob: '0.5823170731707317'
        rate_of_exact_mw_simil: '0.5823170731707317'
        rate_of_exact_nominal_mw_prob: '0.6134146341463415'
        rate_of_exact_nominal_mw_simil: '0.6134146341463415'
        rate_of_mw_difference_less_than_1_best_prob: '0.6365853658536585'
        rate_of_mw_difference_less_than_1_best_simil: '0.6365853658536585'
    num_datapoints_tested: '1640'
    num_empty_preds: '12'
    num_predictions_at_k_counter: '[1640]'
    precise_preds_stats:
        num_precise_preds_probsort: '559'
        num_precise_preds_similsort: '559'
        rate_of_precise_preds_probsort: '0.3408536585365854'
        rate_of_precise_preds_similsort: '0.3408536585365854'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 560)])
        num_1_hits_as_first_probsort: '560'
        num_1_hits_as_first_similsort: '560'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '1'
        rate_of_1_hits_as_first_probsort: '0.34146341463414637'
        rate_of_1_hits_as_first_similsort: '0.34146341463414637'
    start_time_utc: 14/12/2024 17:31:24
    threshold_stats:
        num_better_than_threshold_probsort: '588'
        num_better_than_threshold_similsort: '588'
        rate_of_better_than_threshold_probsort: '0.35853658536585364'
        rate_of_better_than_threshold_similsort: '0.35853658536585364'
        threshold: '0.85'
    topk_probsort: '[0.6772364259076231]'
    topk_similsort: '[0.6772364259076231]'
