command: predict.py --checkpoint ../checkpoints/finetune_clean/smooth-totem-563_exp6_72perc_frozen/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/10/2024 09:04:33
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 04/10/2024 19:39:58
generation_time: '10:35:21'
wall_time_utc: '10:35:25'
evaluation_0:
    average_num_of_predictions: '0.9768960499698336'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.18914361027161952'
        mean_fpsd_score_similsort: '0.18914361027161952'
        rate_of_BART_wins_probsort: '0.669056322532562'
        rate_of_BART_wins_similsort: '0.669056322532562'
        rate_of_ties_probsort: '0.12531497320509635'
        rate_of_ties_similsort: '0.12531497320509635'
        ties:
            mean_tie_simils_probsort: '0.7470576072278637'
            mean_tie_simils_similsort: '0.7470576072278637'
            num_of_ties_probsort: '3531'
            num_of_ties_simils_equal_to_1_probsort: '1613'
            num_of_ties_simils_equal_to_1_similsort: '1613'
            num_of_ties_similsort: '3531'
            rate_of_ties_simils_equal_to_1_probsort: '0.45681110167091477'
            rate_of_ties_simils_equal_to_1_similsort: '0.45681110167091477'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 16526 / 27526
        num_at_least_one_correct_formula: '16526'
        num_correct_formulas_at_best_prob: '16526'
        num_correct_formulas_at_best_simil: '16526'
        rate_of_all_correct_formulas: '0.6003778246021942'
        rate_of_at_least_one_correct_formula: '0.5865067253433651'
        rate_of_correct_formulas_at_best_prob: '0.5865067253433651'
        rate_of_correct_formulas_at_best_simil: '0.5865067253433651'
    hit_at_k_prob: '[(1, 0.33129857685346203)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    num_datapoints_tested: '28177'
    num_empty_preds: '651'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '8789'
        num_precise_preds_similsort: '8789'
        rate_of_precise_preds_probsort: '0.31192107037654826'
        rate_of_precise_preds_similsort: '0.31192107037654826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 9335)])
        num_1_hits_as_first_probsort: '9335'
        num_1_hits_as_first_similsort: '9335'
        num_fp_simil_fail_prob: '546'
        num_fp_simil_fail_simil: '546'
        rate_of_1_hits_as_first_probsort: '0.33129857685346203'
        rate_of_1_hits_as_first_similsort: '0.33129857685346203'
    start_time_utc: 06/10/2024 23:57:15
    threshold_stats:
        num_better_than_threshold_probsort: '9638'
        num_better_than_threshold_similsort: '9638'
        rate_of_better_than_threshold_probsort: '0.34205202824999115'
        rate_of_better_than_threshold_similsort: '0.34205202824999115'
        threshold: '0.85'
    topk_probsort: '[0.5764594036131822]'
    topk_similsort: '[0.5764594036131822]'
evaluation_1:
    average_num_of_predictions: '0.9768960499698336'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.18914361027161952'
        mean_fpsd_score_similsort: '0.18914361027161952'
        rate_of_BART_wins_probsort: '0.669056322532562'
        rate_of_BART_wins_similsort: '0.669056322532562'
        rate_of_ties_probsort: '0.12531497320509635'
        rate_of_ties_similsort: '0.12531497320509635'
        ties:
            mean_tie_simils_probsort: '0.7470576072278637'
            mean_tie_simils_similsort: '0.7470576072278637'
            num_of_ties_probsort: '3531'
            num_of_ties_simils_equal_to_1_probsort: '1613'
            num_of_ties_simils_equal_to_1_similsort: '1613'
            num_of_ties_similsort: '3531'
            rate_of_ties_simils_equal_to_1_probsort: '0.45681110167091477'
            rate_of_ties_simils_equal_to_1_similsort: '0.45681110167091477'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 16526 / 27526
        num_at_least_one_correct_formula: '16526'
        num_correct_formulas_at_best_prob: '16526'
        num_correct_formulas_at_best_simil: '16526'
        rate_of_all_correct_formulas: '0.6003778246021942'
        rate_of_at_least_one_correct_formula: '0.5865067253433651'
        rate_of_correct_formulas_at_best_prob: '0.5865067253433651'
        rate_of_correct_formulas_at_best_simil: '0.5865067253433651'
    hit_at_k_prob: '[(1, 0.33129857685346203)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.682891512600777'
        mean_absolute_mw_difference_best_simil: '6.682891512600777'
        mean_relative_mw_difference_best_prob: 2.40%
        mean_relative_mw_difference_best_simil: 2.40%
        rate_of_exact_mw_prob: '0.5752919047450048'
        rate_of_exact_mw_simil: '0.5752919047450048'
        rate_of_exact_nominal_mw_prob: '0.6361571494481315'
        rate_of_exact_nominal_mw_simil: '0.6361571494481315'
        rate_of_mw_difference_less_than_1_best_prob: '0.6762607800688505'
        rate_of_mw_difference_less_than_1_best_simil: '0.6762607800688505'
    num_datapoints_tested: '28177'
    num_empty_preds: '651'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '8789'
        num_precise_preds_similsort: '8789'
        rate_of_precise_preds_probsort: '0.31192107037654826'
        rate_of_precise_preds_similsort: '0.31192107037654826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 9335)])
        num_1_hits_as_first_probsort: '9335'
        num_1_hits_as_first_similsort: '9335'
        num_fp_simil_fail_prob: '546'
        num_fp_simil_fail_simil: '546'
        rate_of_1_hits_as_first_probsort: '0.33129857685346203'
        rate_of_1_hits_as_first_similsort: '0.33129857685346203'
    start_time_utc: 04/11/2024 14:06:27
    threshold_stats:
        num_better_than_threshold_probsort: '9638'
        num_better_than_threshold_similsort: '9638'
        rate_of_better_than_threshold_probsort: '0.34205202824999115'
        rate_of_better_than_threshold_similsort: '0.34205202824999115'
        threshold: '0.85'
    topk_probsort: '[0.5764594036131822]'
    topk_similsort: '[0.5764594036131822]'
evaluation_2:
    average_num_of_predictions: '0.9768960499698336'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.18914361027161952'
        mean_fpsd_score_similsort: '0.18914361027161952'
        rate_of_BART_wins_probsort: '0.669056322532562'
        rate_of_BART_wins_similsort: '0.669056322532562'
        rate_of_ties_probsort: '0.12531497320509635'
        rate_of_ties_similsort: '0.12531497320509635'
        ties:
            mean_tie_simils_probsort: '0.7470576072278637'
            mean_tie_simils_similsort: '0.7470576072278637'
            num_of_ties_probsort: '3531'
            num_of_ties_simils_equal_to_1_probsort: '1613'
            num_of_ties_simils_equal_to_1_similsort: '1613'
            num_of_ties_similsort: '3531'
            rate_of_ties_simils_equal_to_1_probsort: '0.45681110167091477'
            rate_of_ties_simils_equal_to_1_similsort: '0.45681110167091477'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 16526 / 27526
        num_at_least_one_correct_formula: '16526'
        num_correct_formulas_at_best_prob: '16526'
        num_correct_formulas_at_best_simil: '16526'
        rate_of_all_correct_formulas: '0.6003778246021942'
        rate_of_at_least_one_correct_formula: '0.5865067253433651'
        rate_of_correct_formulas_at_best_prob: '0.5865067253433651'
        rate_of_correct_formulas_at_best_simil: '0.5865067253433651'
    hit_at_k_prob: '[(1, 0.33129857685346203)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.682891512600777'
        mean_absolute_mw_difference_best_simil: '6.682891512600777'
        mean_relative_mw_difference_best_prob: 2.40%
        mean_relative_mw_difference_best_simil: 2.40%
        rate_of_exact_mw_prob: '0.5752919047450048'
        rate_of_exact_mw_simil: '0.5752919047450048'
        rate_of_exact_nominal_mw_prob: '0.6361571494481315'
        rate_of_exact_nominal_mw_simil: '0.6361571494481315'
        rate_of_mw_difference_less_than_1_best_prob: '0.6762607800688505'
        rate_of_mw_difference_less_than_1_best_simil: '0.6762607800688505'
    num_datapoints_tested: '28177'
    num_empty_preds: '651'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '8789'
        num_precise_preds_similsort: '8789'
        rate_of_precise_preds_probsort: '0.31192107037654826'
        rate_of_precise_preds_similsort: '0.31192107037654826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 9335)])
        num_1_hits_as_first_probsort: '9335'
        num_1_hits_as_first_similsort: '9335'
        num_fp_simil_fail_prob: '546'
        num_fp_simil_fail_simil: '546'
        rate_of_1_hits_as_first_probsort: '0.33129857685346203'
        rate_of_1_hits_as_first_similsort: '0.33129857685346203'
    start_time_utc: 04/11/2024 14:09:53
    threshold_stats:
        num_better_than_threshold_probsort: '9638'
        num_better_than_threshold_similsort: '9638'
        rate_of_better_than_threshold_probsort: '0.34205202824999115'
        rate_of_better_than_threshold_similsort: '0.34205202824999115'
        threshold: '0.85'
    topk_probsort: '[0.5764594036131822]'
    topk_similsort: '[0.5764594036131822]'
evaluation_3:
    average_num_of_predictions: '0.9768960499698336'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.18914361027161952'
        mean_fpsd_score_similsort: '0.18914361027161952'
        rate_of_BART_wins_probsort: '0.669056322532562'
        rate_of_BART_wins_similsort: '0.669056322532562'
        rate_of_ties_probsort: '0.12531497320509635'
        rate_of_ties_similsort: '0.12531497320509635'
        ties:
            mean_tie_simils_probsort: '0.7470576072278637'
            mean_tie_simils_similsort: '0.7470576072278637'
            num_of_ties_probsort: '3531'
            num_of_ties_simils_equal_to_1_probsort: '1613'
            num_of_ties_simils_equal_to_1_similsort: '1613'
            num_of_ties_similsort: '3531'
            rate_of_ties_simils_equal_to_1_probsort: '0.45681110167091477'
            rate_of_ties_simils_equal_to_1_similsort: '0.45681110167091477'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:31
    formula_stats:
        num_all_correct_formulas: 16526 / 27526
        num_at_least_one_correct_formula: '16526'
        num_correct_formulas_at_best_prob: '16526'
        num_correct_formulas_at_best_simil: '16526'
        rate_of_all_correct_formulas: '0.6003778246021942'
        rate_of_at_least_one_correct_formula: '0.5865067253433651'
        rate_of_correct_formulas_at_best_prob: '0.5865067253433651'
        rate_of_correct_formulas_at_best_simil: '0.5865067253433651'
    hit_at_k_prob: '[(1, 0.33129857685346203)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.682891512600777'
        mean_absolute_mw_difference_best_simil: '6.682891512600777'
        mean_relative_mw_difference_best_prob: 2.40%
        mean_relative_mw_difference_best_simil: 2.40%
        rate_of_exact_mw_prob: '0.5752919047450048'
        rate_of_exact_mw_simil: '0.5752919047450048'
        rate_of_exact_nominal_mw_prob: '0.6361571494481315'
        rate_of_exact_nominal_mw_simil: '0.6361571494481315'
        rate_of_mw_difference_less_than_1_best_prob: '0.6762607800688505'
        rate_of_mw_difference_less_than_1_best_simil: '0.6762607800688505'
    num_datapoints_tested: '28177'
    num_empty_preds: '651'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '8789'
        num_precise_preds_similsort: '8789'
        rate_of_precise_preds_probsort: '0.31192107037654826'
        rate_of_precise_preds_similsort: '0.31192107037654826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 9335)])
        num_1_hits_as_first_probsort: '9335'
        num_1_hits_as_first_similsort: '9335'
        num_fp_simil_fail_prob: '546'
        num_fp_simil_fail_simil: '546'
        rate_of_1_hits_as_first_probsort: '0.33129857685346203'
        rate_of_1_hits_as_first_similsort: '0.33129857685346203'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '9638'
        num_better_than_threshold_similsort: '9638'
        rate_of_better_than_threshold_probsort: '0.34205202824999115'
        rate_of_better_than_threshold_similsort: '0.34205202824999115'
        threshold: '0.85'
    topk_probsort: '[0.5764594036131822]'
    topk_similsort: '[0.5764594036131822]'
