command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_cayman_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
  data_split: all
  dataset_name: Cayman_library
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 15:25:32
generation_time: 00:16:57
wall_time_utc: 00:17:08
evaluation_0:
    average_num_of_predictions: '0.9957356076759062'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 194 / 467
        num_at_least_one_correct_formula: '194'
        num_correct_formulas_at_best_prob: '194'
        num_correct_formulas_at_best_simil: '194'
        rate_of_all_correct_formulas: '0.41541755888650966'
        rate_of_at_least_one_correct_formula: '0.4136460554371002'
        rate_of_correct_formulas_at_best_prob: '0.4136460554371002'
        rate_of_correct_formulas_at_best_simil: '0.4136460554371002'
    hit_at_k_prob: '[(1, 0.2068230277185501)]'
    labels_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '32.71178006378159'
        mean_absolute_mw_difference_best_simil: '32.71178006378159'
        mean_relative_mw_difference_best_prob: 11.52%
        mean_relative_mw_difference_best_simil: 11.52%
        rate_of_exact_mw_prob: '0.4051172707889126'
        rate_of_exact_mw_simil: '0.4051172707889126'
        rate_of_exact_nominal_mw_prob: '0.44349680170575695'
        rate_of_exact_nominal_mw_simil: '0.44349680170575695'
        rate_of_mw_difference_less_than_1_best_prob: '0.4626865671641791'
        rate_of_mw_difference_less_than_1_best_simil: '0.4626865671641791'
    num_datapoints_tested: '469'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[469]'
    precise_preds_stats:
        num_precise_preds_probsort: '97'
        num_precise_preds_similsort: '97'
        rate_of_precise_preds_probsort: '0.2068230277185501'
        rate_of_precise_preds_similsort: '0.2068230277185501'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 97)])
        num_1_hits_as_first_probsort: '97'
        num_1_hits_as_first_similsort: '97'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.2068230277185501'
        rate_of_1_hits_as_first_similsort: '0.2068230277185501'
    start_time_utc: 14/12/2024 17:31:01
    threshold_stats:
        num_better_than_threshold_probsort: '117'
        num_better_than_threshold_similsort: '117'
        rate_of_better_than_threshold_probsort: '0.24946695095948826'
        rate_of_better_than_threshold_similsort: '0.24946695095948826'
        threshold: '0.85'
    topk_probsort: '[0.6080728641528721]'
    topk_similsort: '[0.6080728641528721]'
