command: predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 11/12/2024 13:15:30
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 13:34:17
generation_time: 00:18:40
wall_time_utc: 00:18:47
evaluation_0:
    average_num_of_predictions: '8.05664194200944'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:56
    formula_stats:
        num_all_correct_formulas: 69566 / 227012
        num_at_least_one_correct_formula: '24003'
        num_correct_formulas_at_best_prob: '18792'
        num_correct_formulas_at_best_simil: '21451'
        rate_of_all_correct_formulas: '0.3064419502052755'
        rate_of_at_least_one_correct_formula: '0.8518649962735565'
        rate_of_correct_formulas_at_best_prob: '0.6669269262164177'
        rate_of_correct_formulas_at_best_simil: '0.7612946729602158'
    hit_at_k_prob: '[(1, 0.41448699293750224), (2, 0.5155623380771551), (3, 0.5633317954359939),
        (4, 0.591475316747702), (5, 0.6116336018738687), (6, 0.6256166376832168),
        (7, 0.6344891223338184), (8, 0.6393867338609505), (9, 0.6421549490719382),
        (10, 0.6433261170458175)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.9532718314801825'
        mean_absolute_mw_difference_best_simil: '6.504192450681887'
        mean_relative_mw_difference_best_prob: 2.12%
        mean_relative_mw_difference_best_simil: 2.29%
        rate_of_exact_mw_prob: '0.6578060119955993'
        rate_of_exact_mw_simil: '0.6854171842282712'
        rate_of_exact_nominal_mw_prob: '0.7015296163537638'
        rate_of_exact_nominal_mw_simil: '0.7073499662845584'
        rate_of_mw_difference_less_than_1_best_prob: '0.7223267203747737'
        rate_of_mw_difference_less_than_1_best_simil: '0.7227171096994002'
    num_datapoints_tested: '28177'
    num_empty_preds: '1'
    num_predictions_at_k_counter: '[28177, 27995, 27615, 26891, 25763, 24114, 21930,
        19156, 15367, 10005]'
    precise_preds_stats:
        num_precise_preds_probsort: '11233'
        num_precise_preds_similsort: '18026'
        rate_of_precise_preds_probsort: '0.39865848032082907'
        rate_of_precise_preds_similsort: '0.6397416332469745'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 15267), (5, 88), (3, 1035), (2, 1405),
            (4, 268), (10, 2), (8, 6), (7, 19), (6, 33), (9, 4)])
        num_1_hits_as_first_probsort: '11679'
        num_1_hits_as_first_similsort: '18127'
        num_fp_simil_fail_prob: '446'
        num_fp_simil_fail_simil: '101'
        rate_of_1_hits_as_first_probsort: '0.41448699293750224'
        rate_of_1_hits_as_first_similsort: '0.6433261170458175'
    start_time_utc: 12/12/2024 14:44:19
    threshold_stats:
        num_better_than_threshold_probsort: '12015'
        num_better_than_threshold_similsort: '18345'
        rate_of_better_than_threshold_probsort: '0.4264116123079107'
        rate_of_better_than_threshold_similsort: '0.651062923661142'
        threshold: '0.85'
    topk_probsort: '[0.6599282546944073, 0.5390847545184546, 0.4882528996348328, 0.4572626501507858,
        0.4372082380380619, 0.41628986889108444, 0.3936835540511196, 0.3716457014922243,
        0.3481205180532352, 0.32539689565271285]'
    topk_similsort: '[0.8036497799249688, 0.5946062679870937, 0.514736845671042, 0.45768599319425207,
        0.41336093871476426, 0.37407873035807565, 0.3372028175051602, 0.3019176608509999,
        0.26840143909283387, 0.23393551422981557]'
