command: predict.py --checkpoint ../checkpoints/finetune/fearless-wildflower-490_rassp1_neims1_224kPretrain_148k/checkpoint-147476
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 31/10/2024 11:46:25
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 31/10/2024 13:12:15
generation_time: 01:25:45
wall_time_utc: 01:25:49
evaluation_0:
    average_num_of_predictions: '0.9845973666465557'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.21353116783169848'
        mean_fpsd_score_similsort: '0.21353116783169848'
        rate_of_BART_wins_probsort: '0.6825779891400788'
        rate_of_BART_wins_similsort: '0.6825779891400788'
        rate_of_ties_probsort: '0.12598928203854207'
        rate_of_ties_similsort: '0.12598928203854207'
        ties:
            mean_tie_simils_probsort: '0.7307071242893971'
            mean_tie_simils_similsort: '0.7307071242893971'
            num_of_ties_probsort: '3550'
            num_of_ties_simils_equal_to_1_probsort: '1535'
            num_of_ties_simils_equal_to_1_similsort: '1535'
            num_of_ties_similsort: '3550'
            rate_of_ties_simils_equal_to_1_probsort: '0.4323943661971831'
            rate_of_ties_simils_equal_to_1_similsort: '0.4323943661971831'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:23
    formula_stats:
        num_all_correct_formulas: 16868 / 27743
        num_at_least_one_correct_formula: '16868'
        num_correct_formulas_at_best_prob: '16868'
        num_correct_formulas_at_best_simil: '16868'
        rate_of_all_correct_formulas: '0.6080092275528962'
        rate_of_at_least_one_correct_formula: '0.5986442843453881'
        rate_of_correct_formulas_at_best_prob: '0.5986442843453881'
        rate_of_correct_formulas_at_best_simil: '0.5986442843453881'
    hit_at_k_prob: '[(1, 0.3574546616034354)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_mw_difference_best_prob: '6.815569336494495'
        mean_mw_difference_best_simil: '6.815569336494495'
        rate_of_exact_mw_prob: '0.5891329807999433'
        rate_of_exact_mw_simil: '0.5891329807999433'
        rate_of_exact_nominal_mw_prob: '0.635944209816517'
        rate_of_exact_nominal_mw_simil: '0.635944209816517'
        rate_of_mw_difference_less_than_1_best_prob: '0.6671043759094297'
        rate_of_mw_difference_less_than_1_best_simil: '0.6671043759094297'
    num_datapoints_tested: '28177'
    num_empty_preds: '434'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '9676'
        num_precise_preds_similsort: '9676'
        rate_of_precise_preds_probsort: '0.3434006459168826'
        rate_of_precise_preds_similsort: '0.3434006459168826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10072)])
        num_1_hits_as_first_probsort: '10072'
        num_1_hits_as_first_similsort: '10072'
        num_fp_simil_fail_prob: '396'
        num_fp_simil_fail_simil: '396'
        rate_of_1_hits_as_first_probsort: '0.3574546616034354'
        rate_of_1_hits_as_first_similsort: '0.3574546616034354'
    start_time_utc: 01/11/2024 13:35:40
    threshold_stats:
        num_better_than_threshold_probsort: '10357'
        num_better_than_threshold_similsort: '10357'
        rate_of_better_than_threshold_probsort: '0.3675692941051212'
        rate_of_better_than_threshold_similsort: '0.3675692941051212'
        threshold: '0.85'
    topk_probsort: '[0.6008469611732611]'
    topk_similsort: '[0.6008469611732611]'
evaluation_1:
    average_num_of_predictions: '0.9845973666465557'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.21353116783169848'
        mean_fpsd_score_similsort: '0.21353116783169848'
        rate_of_BART_wins_probsort: '0.6825779891400788'
        rate_of_BART_wins_similsort: '0.6825779891400788'
        rate_of_ties_probsort: '0.12598928203854207'
        rate_of_ties_similsort: '0.12598928203854207'
        ties:
            mean_tie_simils_probsort: '0.7307071242893971'
            mean_tie_simils_similsort: '0.7307071242893971'
            num_of_ties_probsort: '3550'
            num_of_ties_simils_equal_to_1_probsort: '1535'
            num_of_ties_simils_equal_to_1_similsort: '1535'
            num_of_ties_similsort: '3550'
            rate_of_ties_simils_equal_to_1_probsort: '0.4323943661971831'
            rate_of_ties_simils_equal_to_1_similsort: '0.4323943661971831'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:32
    formula_stats:
        num_all_correct_formulas: 16868 / 27743
        num_at_least_one_correct_formula: '16868'
        num_correct_formulas_at_best_prob: '16868'
        num_correct_formulas_at_best_simil: '16868'
        rate_of_all_correct_formulas: '0.6080092275528962'
        rate_of_at_least_one_correct_formula: '0.5986442843453881'
        rate_of_correct_formulas_at_best_prob: '0.5986442843453881'
        rate_of_correct_formulas_at_best_simil: '0.5986442843453881'
    hit_at_k_prob: '[(1, 0.3574546616034354)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.815569336494495'
        mean_absolute_mw_difference_best_simil: '6.815569336494495'
        mean_relative_mw_difference_best_prob: 2.46%
        mean_relative_mw_difference_best_simil: 2.46%
        rate_of_exact_mw_prob: '0.5891329807999433'
        rate_of_exact_mw_simil: '0.5891329807999433'
        rate_of_exact_nominal_mw_prob: '0.635944209816517'
        rate_of_exact_nominal_mw_simil: '0.635944209816517'
        rate_of_mw_difference_less_than_1_best_prob: '0.6671043759094297'
        rate_of_mw_difference_less_than_1_best_simil: '0.6671043759094297'
    num_datapoints_tested: '28177'
    num_empty_preds: '434'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '9676'
        num_precise_preds_similsort: '9676'
        rate_of_precise_preds_probsort: '0.3434006459168826'
        rate_of_precise_preds_similsort: '0.3434006459168826'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10072)])
        num_1_hits_as_first_probsort: '10072'
        num_1_hits_as_first_similsort: '10072'
        num_fp_simil_fail_prob: '396'
        num_fp_simil_fail_simil: '396'
        rate_of_1_hits_as_first_probsort: '0.3574546616034354'
        rate_of_1_hits_as_first_similsort: '0.3574546616034354'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '10357'
        num_better_than_threshold_similsort: '10357'
        rate_of_better_than_threshold_probsort: '0.3675692941051212'
        rate_of_better_than_threshold_similsort: '0.3675692941051212'
        threshold: '0.85'
    topk_probsort: '[0.6008469611732611]'
    topk_similsort: '[0.6008469611732611]'
