command: predict.py --checkpoint ../checkpoints/finetune_clean/jolly-lion-562_exp6_45perc_frozen/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 11:40:09
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 09/10/2024 06:25:05
generation_time: '18:44:52'
wall_time_utc: '18:44:56'
evaluation_0:
    average_num_of_predictions: '8.481385527203038'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.21153944311710834'
        mean_fpsd_score_similsort: '0.36899730896738864'
        rate_of_spectus_wins_probsort: '0.692302232317138'
        rate_of_spectus_wins_similsort: '0.855236540440785'
        rate_of_ties_probsort: '0.08624055080384711'
        rate_of_ties_similsort: '0.08624055080384711'
        ties:
            mean_tie_simils_probsort: '0.8417979385162565'
            mean_tie_simils_similsort: '0.8808976278927865'
            num_of_ties_probsort: '2430'
            num_of_ties_simils_equal_to_1_probsort: '1655'
            num_of_ties_simils_equal_to_1_similsort: '1780'
            num_of_ties_similsort: '2430'
            rate_of_ties_simils_equal_to_1_probsort: '0.6810699588477366'
            rate_of_ties_simils_equal_to_1_similsort: '0.7325102880658436'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:13
    formula_stats:
        num_all_correct_formulas: 72649 / 238980
        num_at_least_one_correct_formula: '22873'
        num_correct_formulas_at_best_prob: '17012'
        num_correct_formulas_at_best_simil: '19699'
        rate_of_all_correct_formulas: '0.3039961503054649'
        rate_of_at_least_one_correct_formula: '0.8117613656528374'
        rate_of_correct_formulas_at_best_prob: '0.6037548355041346'
        rate_of_correct_formulas_at_best_simil: '0.6991163005288001'
    hit_at_k_prob: '[(1, 0.3397096923022323), (2, 0.4312027540192355), (3, 0.4811370976328211),
        (4, 0.5110551158746496), (5, 0.5323845689746957), (6, 0.5481066117755616),
        (7, 0.559498882066934), (8, 0.5671292188664514), (9, 0.5716719310075593),
        (10, 0.5732689782446676)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.588312029461337'
        mean_absolute_mw_difference_best_simil: '6.908246252444043'
        mean_relative_mw_difference_best_prob: 2.33%
        mean_relative_mw_difference_best_simil: 2.45%
        rate_of_exact_mw_prob: '0.5933207935550272'
        rate_of_exact_mw_simil: '0.6405933917734322'
        rate_of_exact_nominal_mw_prob: '0.6469815807218654'
        rate_of_exact_nominal_mw_simil: '0.6712566987259112'
        rate_of_mw_difference_less_than_1_best_prob: '0.6865528622635483'
        rate_of_mw_difference_less_than_1_best_simil: '0.7001100188096675'
    num_datapoints_tested: '28177'
    num_empty_preds: '6'
    num_predictions_at_k_counter: '[28177, 28138, 28006, 27661, 26957, 25771, 24024,
        21398, 17507, 11347]'
    precise_preds_stats:
        num_precise_preds_probsort: '9045'
        num_precise_preds_similsort: '16028'
        rate_of_precise_preds_probsort: '0.32100649465876424'
        rate_of_precise_preds_similsort: '0.5688327359193669'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 13580), (2, 1260), (6, 57), (3, 772),
            (5, 129), (4, 283), (8, 22), (7, 31), (9, 11), (10, 8)])
        num_1_hits_as_first_probsort: '9572'
        num_1_hits_as_first_similsort: '16153'
        num_fp_simil_fail_prob: '527'
        num_fp_simil_fail_simil: '125'
        rate_of_1_hits_as_first_probsort: '0.3397096923022323'
        rate_of_1_hits_as_first_similsort: '0.5732689782446676'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '9897'
        num_better_than_threshold_similsort: '16371'
        rate_of_better_than_threshold_probsort: '0.3512439223480143'
        rate_of_better_than_threshold_similsort: '0.5810057848599922'
        threshold: '0.85'
    topk_probsort: '[0.5988552364586709, 0.5002453463871216, 0.46041049651798294,
        0.43298988109204833, 0.41839080834577425, 0.40410166239402034, 0.39014265267690923,
        0.37116419653297006, 0.3518887473456793, 0.3314585832373035]'
    topk_similsort: '[0.7563131023089512, 0.5649899725044443, 0.49106670638092054,
        0.4401585214367792, 0.3990570799731964, 0.3632345878286121, 0.329782463132161,
        0.2960659595154991, 0.2640038412452636, 0.23052325804456233]'
