command: predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_test_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/test.jsonl
  data_split: test
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 11/12/2024 13:15:30
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 13:40:02
generation_time: 00:24:25
wall_time_utc: 00:24:31
evaluation_0:
    average_num_of_predictions: '8.073053383804437'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:57
    formula_stats:
        num_all_correct_formulas: 70138 / 228201
        num_at_least_one_correct_formula: '24156'
        num_correct_formulas_at_best_prob: '18884'
        num_correct_formulas_at_best_simil: '21684'
        rate_of_all_correct_formulas: '0.30735185209530197'
        rate_of_at_least_one_correct_formula: '0.8545653942760109'
        rate_of_correct_formulas_at_best_prob: '0.668058159691513'
        rate_of_correct_formulas_at_best_simil: '0.7671135953585453'
    hit_at_k_prob: '[(1, 0.41702338415820567), (2, 0.5145576113489227), (3, 0.5632716595323168),
        (4, 0.5927760285845686), (5, 0.6133300314854777), (6, 0.6289312626030353),
        (7, 0.6388014292284289), (8, 0.6448862631336895), (9, 0.6476810414971521),
        (10, 0.6485654650298935)]'
    labels_path: data/nist/test.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.881469809226968'
        mean_absolute_mw_difference_best_simil: '6.2752431122502'
        mean_relative_mw_difference_best_prob: 2.15%
        mean_relative_mw_difference_best_simil: 2.23%
        rate_of_exact_mw_prob: '0.6564545229419464'
        rate_of_exact_mw_simil: '0.6882230162380161'
        rate_of_exact_nominal_mw_prob: '0.7017370078183041'
        rate_of_exact_nominal_mw_simil: '0.7138359217462058'
        rate_of_mw_difference_less_than_1_best_prob: '0.7212297024799236'
        rate_of_mw_difference_less_than_1_best_simil: '0.7281635829766159'
    num_datapoints_tested: '28267'
    num_empty_preds: '5'
    num_predictions_at_k_counter: '[28267, 28096, 27725, 27030, 25945, 24304, 22129,
        19253, 15494, 9963]'
    precise_preds_stats:
        num_precise_preds_probsort: '11295'
        num_precise_preds_similsort: '18235'
        rate_of_precise_preds_probsort: '0.39958255209254606'
        rate_of_precise_preds_similsort: '0.6450985247815474'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 15454), (2, 1346), (3, 1108), (5, 99),
            (4, 275), (8, 5), (6, 32), (10, 4), (7, 10)])
        num_1_hits_as_first_probsort: '11788'
        num_1_hits_as_first_similsort: '18333'
        num_fp_simil_fail_prob: '493'
        num_fp_simil_fail_simil: '98'
        rate_of_1_hits_as_first_probsort: '0.41702338415820567'
        rate_of_1_hits_as_first_similsort: '0.6485654650298935'
    start_time_utc: 12/12/2024 14:44:19
    threshold_stats:
        num_better_than_threshold_probsort: '12105'
        num_better_than_threshold_similsort: '18527'
        rate_of_better_than_threshold_probsort: '0.4282378745533661'
        rate_of_better_than_threshold_similsort: '0.6554285916439665'
        threshold: '0.85'
    topk_probsort: '[0.6626561653801288, 0.5396275922398257, 0.4907689366501643, 0.460589996721156,
        0.4384417115344472, 0.41975706387609335, 0.3965383758731694, 0.3746128973668227,
        0.34973922852172457, 0.3251545812382574]'
    topk_similsort: '[0.8067491758203265, 0.5978956985001496, 0.5178871140254788,
        0.4597789840588695, 0.4155815827556828, 0.3754107343435144, 0.33876051244488725,
        0.3037671465696342, 0.26993269213563265, 0.23581137675382083]'
