command: predict.py --checkpoint ../checkpoints/finetune_clean/valiant-totem-557_exp4_neims/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 00:21:08
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 08/10/2024 19:02:40
generation_time: '18:41:27'
wall_time_utc: '18:41:31'
evaluation_0:
    average_num_of_predictions: '8.558327714093055'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23449698532976057'
        mean_fpsd_score_similsort: '0.38626824293353346'
        rate_of_BART_wins_probsort: '0.7115732689782447'
        rate_of_BART_wins_similsort: '0.8657415622670973'
        rate_of_ties_probsort: '0.0879440678567626'
        rate_of_ties_similsort: '0.0879440678567626'
        ties:
            mean_tie_simils_probsort: '0.8301347159174279'
            mean_tie_simils_similsort: '0.8686041407346804'
            num_of_ties_probsort: '2478'
            num_of_ties_simils_equal_to_1_probsort: '1655'
            num_of_ties_simils_equal_to_1_similsort: '1784'
            num_of_ties_similsort: '2478'
            rate_of_ties_simils_equal_to_1_probsort: '0.6678773204196933'
            rate_of_ties_simils_equal_to_1_similsort: '0.7199354317998385'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:14
    formula_stats:
        num_all_correct_formulas: 72909 / 241148
        num_at_least_one_correct_formula: '23201'
        num_correct_formulas_at_best_prob: '17563'
        num_correct_formulas_at_best_simil: '20288'
        rate_of_all_correct_formulas: '0.3023413007779455'
        rate_of_at_least_one_correct_formula: '0.8234020655144266'
        rate_of_correct_formulas_at_best_prob: '0.6233097916740604'
        rate_of_correct_formulas_at_best_simil: '0.7200198743656173'
    hit_at_k_prob: '[(1, 0.3684210526315789), (2, 0.46456329630549736), (3, 0.510664726550023),
        (4, 0.5407247045462611), (5, 0.5632253256201867), (6, 0.5770664016751251),
        (7, 0.5872165241154133), (8, 0.5939596124498705), (9, 0.5975440962487135),
        (10, 0.598892713915605)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.359793048398119'
        mean_absolute_mw_difference_best_simil: '6.973013529554457'
        mean_relative_mw_difference_best_prob: 2.27%
        mean_relative_mw_difference_best_simil: 2.46%
        rate_of_exact_mw_prob: '0.6137984881286155'
        rate_of_exact_mw_simil: '0.6475139298009015'
        rate_of_exact_nominal_mw_prob: '0.6617453951804664'
        rate_of_exact_nominal_mw_simil: '0.6745927529545374'
        rate_of_mw_difference_less_than_1_best_prob: '0.6946800582034993'
        rate_of_mw_difference_less_than_1_best_simil: '0.6968804343968485'
    num_datapoints_tested: '28177'
    num_empty_preds: '1'
    num_predictions_at_k_counter: '[28177, 28109, 27890, 27517, 26924, 25895, 24292,
        21922, 18216, 12207]'
    precise_preds_stats:
        num_precise_preds_probsort: '9869'
        num_precise_preds_similsort: '16754'
        rate_of_precise_preds_probsort: '0.35025020406714696'
        rate_of_precise_preds_similsort: '0.5945984313447138'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 14125), (2, 1194), (9, 9), (3, 950),
            (7, 49), (5, 158), (4, 295), (6, 66), (8, 21), (10, 8)])
        num_1_hits_as_first_probsort: '10381'
        num_1_hits_as_first_similsort: '16875'
        num_fp_simil_fail_prob: '512'
        num_fp_simil_fail_simil: '121'
        rate_of_1_hits_as_first_probsort: '0.3684210526315789'
        rate_of_1_hits_as_first_similsort: '0.598892713915605'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '10689'
        num_better_than_threshold_similsort: '17070'
        rate_of_better_than_threshold_probsort: '0.37935195372112007'
        rate_of_better_than_threshold_similsort: '0.6058132519430741'
        threshold: '0.85'
    topk_probsort: '[0.6218127786713232, 0.5190235334187269, 0.47700972956047905,
        0.45303794993707025, 0.43748245739696423, 0.4212747079301559, 0.4043994179859661,
        0.3864647886893115, 0.36415025332822115, 0.3428630430392002]'
    topk_similsort: '[0.773584036275096, 0.5861967848090412, 0.5122312628534826, 0.4599560085291554,
        0.4187662810971032, 0.38145829436293593, 0.34663712922933343, 0.31230247735371625,
        0.2781094705161284, 0.24405928590383605]'
