command: ../predict.py --checkpoint ../checkpoints/finetune_clean/sleek-cloud-581_9M_448+296k/checkpoint-294952
  --output-folder predictions --config-file configs/predict_mona_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
  data_split: all
  dataset_name: MONA_GCMS
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 12/12/2024 15:08:23
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 12/12/2024 16:42:11
generation_time: 01:33:43
wall_time_utc: 01:33:47
evaluation_0:
    average_num_of_predictions: '0.9884346959122632'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:05
    formula_stats:
        num_all_correct_formulas: 1898 / 4957
        num_at_least_one_correct_formula: '1898'
        num_correct_formulas_at_best_prob: '1898'
        num_correct_formulas_at_best_simil: '1898'
        rate_of_all_correct_formulas: '0.38289287875731287'
        rate_of_at_least_one_correct_formula: '0.3784646061814556'
        rate_of_correct_formulas_at_best_prob: '0.3784646061814556'
        rate_of_correct_formulas_at_best_simil: '0.3784646061814556'
    hit_at_k_prob: '[(1, 0.21375872382851446)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '61.08000270124265'
        mean_absolute_mw_difference_best_simil: '61.08000270124265'
        mean_relative_mw_difference_best_prob: 36.16%
        mean_relative_mw_difference_best_simil: 36.16%
        rate_of_exact_mw_prob: '0.3742771684945165'
        rate_of_exact_mw_simil: '0.3742771684945165'
        rate_of_exact_nominal_mw_prob: '0.41774675972083747'
        rate_of_exact_nominal_mw_simil: '0.41774675972083747'
        rate_of_mw_difference_less_than_1_best_prob: '0.4370887337986042'
        rate_of_mw_difference_less_than_1_best_simil: '0.4370887337986042'
    num_datapoints_tested: '5015'
    num_empty_preds: '58'
    num_predictions_at_k_counter: '[5015]'
    precise_preds_stats:
        num_precise_preds_probsort: '1032'
        num_precise_preds_similsort: '1032'
        rate_of_precise_preds_probsort: '0.2057826520438684'
        rate_of_precise_preds_similsort: '0.2057826520438684'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1072)])
        num_1_hits_as_first_probsort: '1072'
        num_1_hits_as_first_similsort: '1072'
        num_fp_simil_fail_prob: '40'
        num_fp_simil_fail_simil: '40'
        rate_of_1_hits_as_first_probsort: '0.21375872382851446'
        rate_of_1_hits_as_first_similsort: '0.21375872382851446'
    start_time_utc: 14/12/2024 17:31:08
    threshold_stats:
        num_better_than_threshold_probsort: '1097'
        num_better_than_threshold_similsort: '1097'
        rate_of_better_than_threshold_probsort: '0.21874376869391823'
        rate_of_better_than_threshold_similsort: '0.21874376869391823'
        threshold: '0.85'
    topk_probsort: '[0.41044621470103515]'
    topk_similsort: '[0.41044621470103515]'
