command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp8_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_cayman_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
  data_split: all
  dataset_name: Cayman_library
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 05/01/2025 21:45:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 05/01/2025 22:44:26
generation_time: 00:59:16
wall_time_utc: 00:59:18
